# Generated by Django 6.0.5 on 2026-06-02 22:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFaltaDeAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoDoFluxo', models.IntegerField(choices=[(0, 'Sem fluxo de água'), (1, 'Com fluxo de água')], verbose_name='Estado do Fluxo de Água')),
                ('dataEHoraDoRegistro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora do Registro')),
            ],
            options={
                'verbose_name': 'Registro de Falta de Água',
                'verbose_name_plural': 'Registros de Falta de Água',
                'ordering': ['dataEHoraDoRegistro', 'id'],
            },
        ),
    ]
