# Generated by Django 6.0.5 on 2026-06-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento_agua', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_metro_cubico', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço por m³ (R$)')),
                ('vazao_media_hora', models.DecimalField(decimal_places=4, default=0.0, help_text='Estimativa de quantos metros cúbicos seriam consumidos por hora.', max_digits=10, verbose_name='Vazão Média por Hora (m³)')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
